SPOTS = {
    "areia_branca": {
        "name": "Areia Branca",
        "lat": 39.273,
        "lon": -9.338,
        "windguru_spot_id": 58060,
        "preferred_wind_dirs": ["NE", "E", "SE"],
        "bad_wind_dirs": ["W", "SW", "S"],
        "ideal_swell_min_m": 1.0,
        "ideal_swell_max_m": 2.4,
        "tide_score": 7,
    },
    "peniche": {
        "name": "Peniche",
        "lat": 39.355,
        "lon": -9.381,
        "windguru_spot_id": 1528,
        "preferred_wind_dirs": ["NE", "E"],
        "bad_wind_dirs": ["W", "SW", "S"],
        "ideal_swell_min_m": 0.9,
        "ideal_swell_max_m": 2.2,
        "tide_score": 9,
    },
    "baleal": {
        "name": "Baleal",
        "lat": 39.374,
        "lon": -9.333,
        "windguru_spot_id": 501140,
        "preferred_wind_dirs": ["NE", "E", "SE"],
        "bad_wind_dirs": ["W", "NW"],
        "ideal_swell_min_m": 0.8,
        "ideal_swell_max_m": 2.0,
        "tide_score": 8,
    },
    "peniche_baleal": {
        "name": "Peniche & Baleal",
        "lat": 39.36,
        "lon": -9.36,
        "windguru_spot_id": 48951,
        "preferred_wind_dirs": ["NE", "E", "SE"],
        "bad_wind_dirs": ["W", "NW"],
        "ideal_swell_min_m": 0.8,
        "ideal_swell_max_m": 2.2,
        "tide_score": 8,
    },
    "supertubos": {
        "name": "Supertubos",
        "lat": 39.345833,
        "lon": -9.368333,
        "windguru_spot_id": 55936,
        "preferred_wind_dirs": ["NE", "E"],
        "bad_wind_dirs": ["W", "SW", "S"],
        "ideal_swell_min_m": 1.2,
        "ideal_swell_max_m": 3.0,
        "tide_score": 8,
    },
    "molhe_leste": {
        "name": "Molhe Leste",
        "lat": 39.350577,
        "lon": -9.36875,
        "windguru_spot_id": 1118700,
        "preferred_wind_dirs": ["N", "NE", "E"],
        "bad_wind_dirs": ["S", "SW", "W"],
        "ideal_swell_min_m": 1.0,
        "ideal_swell_max_m": 2.8,
        "tide_score": 7,
    },
    "consolacao": {
        "name": "Consolacao",
        "lat": 39.325408,
        "lon": -9.361144,
        "windguru_spot_id": 1185514,
        "preferred_wind_dirs": ["E", "SE"],
        "bad_wind_dirs": ["W", "SW"],
        "ideal_swell_min_m": 1.0,
        "ideal_swell_max_m": 3.0,
        "tide_score": 7,
    },
    "lagido": {
        "name": "Lagido",
        "lat": 39.37,
        "lon": -9.33,
        "windguru_spot_id": 39832,
        "preferred_wind_dirs": ["S", "SE", "E"],
        "bad_wind_dirs": ["N", "NW", "W"],
        "ideal_swell_min_m": 0.8,
        "ideal_swell_max_m": 2.4,
        "tide_score": 8,
    },
    "prainha_baleal": {
        "name": "Prainha Baleal",
        "lat": 39.374121,
        "lon": -9.338166,
        "windguru_spot_id": 1081569,
        "preferred_wind_dirs": ["S", "SE", "E"],
        "bad_wind_dirs": ["N", "NW", "W"],
        "ideal_swell_min_m": 0.7,
        "ideal_swell_max_m": 2.0,
        "tide_score": 8,
    },
    "cantinho_da_baia": {
        "name": "Cantinho da Baia",
        "lat": 39.372261,
        "lon": -9.340053,
        "windguru_spot_id": 500477,
        "preferred_wind_dirs": ["S", "SE", "E"],
        "bad_wind_dirs": ["N", "NW", "W"],
        "ideal_swell_min_m": 0.6,
        "ideal_swell_max_m": 1.8,
        "tide_score": 8,
    },
    "almagreira": {
        "name": "Almagreira",
        "lat": 39.379166,
        "lon": -9.314609,
        "windguru_spot_id": 1228141,
        "preferred_wind_dirs": ["E", "SE"],
        "bad_wind_dirs": ["W", "NW", "SW"],
        "ideal_swell_min_m": 1.0,
        "ideal_swell_max_m": 2.5,
        "tide_score": 7,
    },
    "papoa": {
        "name": "Papoa",
        "lat": 39.37448,
        "lon": -9.377964,
        "windguru_spot_id": 1138778,
        "preferred_wind_dirs": ["E", "SE", "S"],
        "bad_wind_dirs": ["W", "NW"],
        "ideal_swell_min_m": 1.0,
        "ideal_swell_max_m": 2.6,
        "tide_score": 6,
    },
}
